api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Document']
    formats:
        # Disabled json-ld to avoid coupling on data structures
        #jsonld:
        #    mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']